services:
  springboot-app:
    build:
      context: . # Répertoire de votre application Spring Boot
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mydb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - mysql
    networks:
      - tp-foyer_network

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - tp-foyer_network


  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube-data:/opt/sonarqube/data
    networks:
      - tp-foyer_network

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8085:8080"  # Port externe différent du port interne de Jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - tp-foyer_network



volumes:
  mysql-data:
  sonarqube-data:
  jenkins_home:

networks:
  tp-foyer_network:
    driver: bridge
