version: '3'
services:
  mysql-db:
    image: mysql:latest
    container_name: docker-compose-mysql-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db
    networks:
      - my-network
    volumes:
      - db:/var/lib/mysql
  spring-boot-app:
    image: mohamedalibrik/tp_foyer:latest
    container_name: app-back
    ports:
      - "8089:8089"
    depends_on:
      - mysql-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/db?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - my-network
    restart: always

networks:
  my-network:

volumes:
  db :