global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'jenkins'
    static_configs:
      - targets: ['jenkins:8080']

  - job_name: 'sonarqube'
    static_configs:
      - targets: ['sonarqube:9000']

  - job_name: 'nexus'
    static_configs:
      - targets: ['nexus_new:8081']

  - job_name: 'springboot'
    static_configs:
      - targets: ['springboot-app:8083']
